kind: pipeline
type: docker
name: default

steps:
- name: Build with Maven
  image: maven:3-jdk-10
  commands:
  - mvn -B package --file pom.xml


- name: Download API Wrapper
  image: maven:3-jdk-10
  commands:
  - curl -O https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/20.11.7.2/vosp-api-wrappers-java-20.11.7.2-dist.zip
  - unzip vosp-api-wrappers-java-20.11.7.2-dist.zip VeracodeJavaAPI.jar


- name: SAST Scan Upload
  image: maven:3-jdk-10
  commands:
  - java -jar VeracodeJavaAPI.jar -vid $VERACODE_API_ID -vkey $VERACODE_API_SECRET -action UploadAndScan -appname "VulnImages-Verademo" -createprofile false -filepath target/verademo.war -version "Commit ${CI_COMMIT_SHA:0:8} - Job $CI_JOB_ID"

  environment:
    VERACODE_API_ID:
      from_secret: VERACODE_API_ID
    VERACODE_API_SECRET:
      from_secret: VERACODE_API_SECRET

- name: SCA Scan
  image: maven:3-jdk-10
  commands:
  - curl -sSL https://download.sourceclear.com/ci.sh 
  - srcclr --version
  environment:
    SRCCLR_API_TOKEN:
      from_secret: SRCCLR_API_TOKEN 
      
- name: Download pipeline code
  image: maven:3-jdk-10
  commands: 
  - curl -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
  - unzip pipeline-scan-LATEST.zip pipeline-scan.jar
      
- name: Pipeline Scan
  image: maven:3-jdk-10
  commands:
  - java -jar pipeline-scan.jar --veracode_api_id $VERACODE_API_ID --veracode_api_key $VERACODE_API_SECRET --file "target/verademo.war"  --fail_on_severity="Very High, High" --fail_on_cwe="80" --timeout "${CI_TIMEOUT}" --project_name "${DRONE_REPO_NAME}" --project_url "${DRONE_REPO_LINK}" --project_ref "${DRONE_COMMIT_REF}" --issue_details true
  environment:
      VERACODE_API_ID:
        from_secret: VERACODE_API_ID
      VERACODE_API_SECRET:
        from_secret: VERACODE_API_SECRET

    
