kind: pipeline
type: docker
name: default

steps:
- name: Build with Maven
  image: maven:3-jdk-10
  commands:
  - mvn -B package --file pom.xml
   
- name: Download pipeline code
  image: maven:3-jdk-10
  commands: 
  - curl -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
  - unzip pipeline-scan-LATEST.zip pipeline-scan.jar
  
- name: Pipeline Scan
  image: maven:3-jdk-10
  commands:
  - java -jar pipeline-scan.jar --veracode_api_id ee3ae20973760304b2727416b1230b6f --veracode_api_key 85f8a751a51c30c27aefcc2b07501f86a5587ff5b63ff7bdbb049285aca6a7352bf1c9b9a8d73e7ba6d90332d6379e805bda527d225fba77bcfa8fb7de2861fc --file "target/verademo.war"
